name: Tests

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typo3: [11.5, 12.4, 13.4]
        php: [8.0, 8.1, 8.2, 8.3]
        exclude:
          - php: "8.0"
            typo3: "12.4"
          - php: "8.0"
            typo3: "13.4"
          - php: "8.1"
            typo3: "13.4"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Prepare env
        run: export TYPO3_PATH_WEB="$PWD/.Build/Web"

      - name: Install dependencies
        run: composer require "typo3/cms-core:^${{ matrix.typo3 }}" "typo3/testing-framework"

      - name: Execute tests
        run: composer test

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer

      - name: Install requirements
        run: composer install

      - name: Execute php-cs-fixer checks
        run: composer code:php-cs-fixer:ci

  messdetector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer

      - name: Install requirements
        run: composer install

      - name: Execute mess checks
        run: composer code:phpmd
